"""Public immutable contracts for Method One."""

from .averages import (
    MethodOneContextualAverages,
    calculate_contextual_average,
    calculate_method_one_contextual_averages,
)
from .base_rates import (
    MethodOneBaseRateExplanation,
    MethodOneBaseRateResult,
    MethodOneParticipantBaseRateExplanation,
    MethodOneWeightedComponent,
    calculate_method_one_base_rates,
)
from .contracts import (
    ContextualAverage,
    ContextualAverageEvidence,
    MethodOneConfiguration,
    MethodOneMetadata,
    MethodOneMultiplierCandidate,
    MethodOneMultiplierResolution,
    MethodOneRateExplanation,
    MethodOneRecencyConfiguration,
    MethodOneRequest,
    MethodOneResult,
    MethodOneSeriesReference,
    MethodOneSeriesRole,
    MethodOneStatisticPeriod,
    MethodOneWeightConfiguration,
    MultiplierCategory,
    MultiplierScope,
    RecencyPolicyCode,
)

__all__ = (
    "MethodOneStatisticPeriod",
    "MethodOneSeriesRole",
    "RecencyPolicyCode",
    "MultiplierScope",
    "MultiplierCategory",
    "MethodOneWeightConfiguration",
    "MethodOneRecencyConfiguration",
    "MethodOneMultiplierCandidate",
    "MethodOneMultiplierResolution",
    "MethodOneConfiguration",
    "MethodOneRequest",
    "MethodOneSeriesReference",
    "ContextualAverage",
    "ContextualAverageEvidence",
    "MethodOneContextualAverages",
    "MethodOneRateExplanation",
    "MethodOneMetadata",
    "MethodOneResult",
    "calculate_contextual_average",
    "calculate_method_one_contextual_averages",
    "MethodOneWeightedComponent",
    "MethodOneParticipantBaseRateExplanation",
    "MethodOneBaseRateExplanation",
    "MethodOneBaseRateResult",
    "calculate_method_one_base_rates",
)
