"""Public immutable contracts for Method One."""

from .averages import (
    MethodOneContextualAverages,
    calculate_contextual_average,
    calculate_method_one_contextual_averages,
)
from .base_rates import (
    MethodOneBaseRateExplanation,
    MethodOneBaseRateResult,
    MethodOneParticipantBaseRateExplanation,
    MethodOneWeightedComponent,
    calculate_method_one_base_rates,
)
from .contracts import (
    METHOD_ONE_MULTIPLIER_CATALOG_VERSION,
    ContextualAverage,
    ContextualAverageEvidence,
    MethodOneConfiguration,
    MethodOneMetadata,
    MethodOneMultiplierCandidate,
    MethodOneMultiplierResolution,
    MethodOneRateExplanation,
    MethodOneRecencyConfiguration,
    MethodOneRequest,
    MethodOneResult,
    MethodOneSeriesReference,
    MethodOneSeriesRole,
    MethodOneStatisticPeriod,
    MethodOneWeightConfiguration,
    MultiplierAppliesTo,
    MultiplierCategory,
    MultiplierScope,
    RecencyPolicyCode,
)
from .multipliers import (
    METHOD_ONE_MULTIPLIER_CATALOG,
    MethodOneAdjustedRateExplanation,
    MethodOneAdjustedRateResult,
    MethodOneMultiplierApplicationStep,
    MethodOneMultiplierCatalog,
    MethodOneMultiplierCatalogEntry,
    apply_method_one_multipliers,
    resolve_method_one_multipliers,
)
from .orchestration import (
    MethodOneFinalExplanation,
    MethodOneFinalResult,
    MethodOnePublicationState,
    run_method_one,
)
from .pricing import (
    MethodOnePricingExplanation,
    MethodOnePricingResult,
    build_method_one_pricing_request,
    price_method_one,
)

__all__ = (
    "MethodOneStatisticPeriod",
    "MethodOneSeriesRole",
    "RecencyPolicyCode",
    "MultiplierScope",
    "MultiplierCategory",
    "MultiplierAppliesTo",
    "METHOD_ONE_MULTIPLIER_CATALOG_VERSION",
    "MethodOneWeightConfiguration",
    "MethodOneRecencyConfiguration",
    "MethodOneMultiplierCandidate",
    "MethodOneMultiplierResolution",
    "MethodOneConfiguration",
    "MethodOneRequest",
    "MethodOneSeriesReference",
    "ContextualAverage",
    "ContextualAverageEvidence",
    "MethodOneContextualAverages",
    "MethodOneRateExplanation",
    "MethodOneMetadata",
    "MethodOneResult",
    "calculate_contextual_average",
    "calculate_method_one_contextual_averages",
    "MethodOneWeightedComponent",
    "MethodOneParticipantBaseRateExplanation",
    "MethodOneBaseRateExplanation",
    "MethodOneBaseRateResult",
    "calculate_method_one_base_rates",
    "MethodOneMultiplierCatalogEntry",
    "MethodOneMultiplierCatalog",
    "METHOD_ONE_MULTIPLIER_CATALOG",
    "MethodOneMultiplierApplicationStep",
    "MethodOneAdjustedRateExplanation",
    "MethodOneAdjustedRateResult",
    "resolve_method_one_multipliers",
    "apply_method_one_multipliers",
    "MethodOnePricingExplanation",
    "MethodOnePricingResult",
    "build_method_one_pricing_request",
    "price_method_one",
    "MethodOnePublicationState",
    "MethodOneFinalExplanation",
    "MethodOneFinalResult",
    "run_method_one",
)
