from datetime import UTC, datetime, timedelta
from typing import Any, cast

import pytest

from lvfi_pricing.core.errors import CalculationError, ErrorCode
from lvfi_pricing.models.method_one import (
    METHOD_ONE_CANONICAL_SCHEMA_VERSION,
    MethodOneFinalResult,
    MethodOneIdentity,
    MethodOnePayload,
    method_one_canonical_bytes,
    method_one_canonical_value,
    method_one_identity,
    method_one_sha256,
    serialize_method_one_final_result,
)
from lvfi_pricing.models.method_one import serialization as implementation
from tests.unit.models.method_one.test_multipliers import candidate
from tests.unit.models.method_one.test_orchestration import request

CONFIGURATION_HASH = "34a33777d62a07b606e599de23dd2889efb24c19c009ce31775cc6ace35e9c76"

# Frozen regression vectors generated by this implementation. They lock the
# canonical bytes of representative Method One final results; any change to the
# serialization, the version constants or the canonical rules fails here.
REGRESSION_RESULT_HASHES: dict[str, str] = {
    "baseline_candidate": (
        "111aa9233114b89f0e77b4f5890f062f06c94ad0d369bc9465a46a13fb741179"
    ),
    "no_multipliers": (
        "d45c701ed25a7099f1d1c1565014cb692306bf6da0a0fb0f4413f9c7aaf98903"
    ),
    "partial_count5": (
        "9705fb42cda6ac71439ca8e6937d281d0f13a1673d7fb0f6af97dc7a7dcdcac2"
    ),
}


def failure(value: object) -> CalculationError:
    assert isinstance(value, CalculationError)
    return value


def final_result(scenario: str) -> MethodOneFinalResult:
    from lvfi_pricing.models.method_one import run_method_one

    if scenario == "baseline_candidate":
        value = run_method_one(request(), (candidate(),))
    elif scenario == "no_multipliers":
        value = run_method_one(request(), ())
    elif scenario == "partial_count5":
        value = run_method_one(request(5), ())
    else:  # pragma: no cover - exhaustive enum
        raise AssertionError(scenario)
    assert isinstance(value, MethodOneFinalResult)
    return value


def test_schema_version_and_registry_are_explicit_and_disjoint() -> None:
    assert METHOD_ONE_CANONICAL_SCHEMA_VERSION == 1
    assert implementation.METHOD_ONE_CANONICAL_SCHEMA_VERSION == 1
    # Pricing Engine contracts nested in a Method One result keep their own
    # canonical schema version and are never re-registered under Method One.
    from lvfi_pricing.engine import PricingResult
    from lvfi_pricing.serialization import CANONICAL_SCHEMA_VERSION

    assert implementation._METHOD_ONE_SCHEMA[PricingResult] == CANONICAL_SCHEMA_VERSION
    assert (
        implementation._METHOD_ONE_SCHEMA[MethodOneFinalResult]
        == METHOD_ONE_CANONICAL_SCHEMA_VERSION
    )


def test_canonical_bytes_are_compact_sorted_utf8_without_whitespace() -> None:
    payload = method_one_canonical_bytes(request())
    assert isinstance(payload, bytes)
    assert payload == method_one_canonical_bytes(request())
    assert not payload.startswith(b"\xef\xbb\xbf")
    assert not payload.endswith(b"\n")
    assert b" " not in payload
    assert b'"away_team_id":"away"' in payload


def test_floats_are_encoded_as_exact_binary64_hex() -> None:
    result = final_result("baseline_candidate")
    bytes_payload = method_one_canonical_bytes(result)
    assert isinstance(bytes_payload, bytes)
    # Every finite float is wrapped in a typed Float envelope using float.hex().
    assert b'"type":"Float"' in bytes_payload
    assert b'"value":"0x' in bytes_payload
    # The home/away base rate (0.5*1.0 + 0.5*4.0 == 2.5) is encoded via hex.
    assert (2.5).hex().encode("ascii") in bytes_payload


def test_datetime_is_normalized_to_utc_iso8601() -> None:
    source = request()
    cutoff = datetime(2026, 1, 31, 12, 0, tzinfo=UTC) - timedelta(days=3)
    object.__setattr__(source, "data_cutoff_at", cutoff)
    bytes_payload = method_one_canonical_bytes(source)
    assert isinstance(bytes_payload, bytes)
    assert b'"type":"DateTime"' in bytes_payload
    assert cutoff.astimezone(UTC).isoformat().encode("ascii") in bytes_payload


def test_enum_and_nested_pricing_engine_values_are_canonical() -> None:
    result = final_result("baseline_candidate")
    bytes_payload = method_one_canonical_bytes(result)
    assert isinstance(bytes_payload, bytes)
    assert b'"enum":"MultiplierCategory"' in bytes_payload
    # Nested PricingResult keeps the Pricing Engine canonical schema version.
    assert b'"type":"PricingResult"' in bytes_payload


def test_deterministic_bytes_independent_of_incidental_construction_order() -> None:
    first = serialize_method_one_final_result(final_result("baseline_candidate"))
    second = serialize_method_one_final_result(final_result("baseline_candidate"))
    assert isinstance(first, MethodOnePayload)
    assert isinstance(second, MethodOnePayload)
    assert first.canonical_bytes == second.canonical_bytes
    assert first.content_hash == second.content_hash


@pytest.mark.parametrize("scenario", tuple(REGRESSION_RESULT_HASHES))
def test_final_result_content_hash_is_frozen(scenario: str) -> None:
    payload = serialize_method_one_final_result(final_result(scenario))
    assert isinstance(payload, MethodOnePayload)
    assert payload.content_hash == REGRESSION_RESULT_HASHES[scenario]
    assert len(payload.content_hash) == 64
    assert payload.content_hash == payload.content_hash.lower()
    assert payload.content_hash.encode("ascii") not in payload.canonical_bytes


def test_envelope_carries_versions_schema_and_root_type() -> None:
    payload = serialize_method_one_final_result(final_result("baseline_candidate"))
    assert isinstance(payload, MethodOnePayload)
    assert payload.schema_version == METHOD_ONE_CANONICAL_SCHEMA_VERSION
    assert payload.root_type == "MethodOneFinalResult"
    assert payload.method_version == "1.0.0"
    assert payload.package_version == "1.1.1"
    assert payload.hash_algorithm == "sha256"
    assert b'"method_version":"1.0.0"' in payload.canonical_bytes
    assert b'"package_version":"1.1.1"' in payload.canonical_bytes
    assert b'"root_type":"MethodOneFinalResult"' in payload.canonical_bytes
    assert b'"schema_version":1' in payload.canonical_bytes


def test_distinct_scenarios_produce_distinct_hashes() -> None:
    hashes: dict[str, str] = {}
    for scenario in REGRESSION_RESULT_HASHES:
        payload = serialize_method_one_final_result(final_result(scenario))
        assert isinstance(payload, MethodOnePayload)
        hashes[scenario] = payload.content_hash
    assert len(set(hashes.values())) == len(hashes)


def test_sha256_is_lowercase_and_changes_with_content() -> None:
    digest = method_one_sha256(request())
    assert isinstance(digest, str)
    assert len(digest) == 64
    assert digest == digest.lower()
    assert digest != method_one_sha256(final_result("baseline_candidate"))


def test_serializers_propagate_typed_errors() -> None:
    assert isinstance(method_one_canonical_value(object()), CalculationError)
    assert isinstance(method_one_canonical_bytes(object()), CalculationError)
    assert isinstance(method_one_sha256(object()), CalculationError)
    assert isinstance(
        serialize_method_one_final_result(cast(MethodOneFinalResult, object())),
        CalculationError,
    )


def test_non_finite_float_and_naive_datetime_are_rejected() -> None:
    nonfinite = final_result("baseline_candidate")
    object.__setattr__(nonfinite.base_rates, "home_base_rate", float("nan"))
    assert (
        failure(method_one_canonical_bytes(nonfinite)).code is ErrorCode.INVALID_NUMBER
    )

    naive = request()
    object.__setattr__(naive, "data_cutoff_at", datetime(2026, 1, 1))
    assert (
        failure(method_one_canonical_bytes(naive)).code is ErrorCode.SERIALIZATION_ERROR
    )


def test_identity_isolates_input_configuration_and_result() -> None:
    identity = method_one_identity(final_result("baseline_candidate"))
    assert isinstance(identity, MethodOneIdentity)
    assert identity.schema_version == METHOD_ONE_CANONICAL_SCHEMA_VERSION
    assert identity.method_version == "1.0.0"
    assert identity.package_version == "1.1.1"
    assert identity.hash_algorithm == "sha256"
    assert identity.result_hash == REGRESSION_RESULT_HASHES["baseline_candidate"]
    assert identity.configuration_hash == CONFIGURATION_HASH
    # Input identity differs from result identity and from configuration identity.
    distinct = {
        identity.input_hash,
        identity.configuration_hash,
        identity.result_hash,
    }
    assert len(distinct) == 3


def test_configuration_hash_is_stable_across_different_samples() -> None:
    identities: dict[str, MethodOneIdentity] = {}
    for scenario in REGRESSION_RESULT_HASHES:
        identity = method_one_identity(final_result(scenario))
        assert isinstance(identity, MethodOneIdentity)
        identities[scenario] = identity
    configs = {identity.configuration_hash for identity in identities.values()}
    assert configs == {CONFIGURATION_HASH}
    # But inputs and results all differ across the scenarios.
    assert len({i.input_hash for i in identities.values()}) == 3
    assert len({i.result_hash for i in identities.values()}) == 3


def test_serializes_individual_method_one_objects() -> None:
    result = final_result("baseline_candidate")
    for value in (
        result.request,
        result.request.configuration,
        result.contextual_averages,
        result.base_rates,
        result.adjusted_rates,
        result.resolutions,
        result.multiplier_candidates,
        result.pricing,
        result.request.series_references[0].snapshot,
    ):
        digest = method_one_sha256(value)
        assert isinstance(digest, str)
        assert len(digest) == 64


def test_identity_comparison_detects_equal_and_divergent_runs() -> None:
    baseline = method_one_identity(final_result("baseline_candidate"))
    repeated = method_one_identity(final_result("baseline_candidate"))
    other = method_one_identity(final_result("no_multipliers"))
    assert isinstance(baseline, MethodOneIdentity)
    assert isinstance(repeated, MethodOneIdentity)
    assert isinstance(other, MethodOneIdentity)
    assert baseline == repeated
    assert baseline != other
    assert baseline.result_hash != other.result_hash


def test_payload_is_immutable() -> None:
    payload = serialize_method_one_final_result(final_result("baseline_candidate"))
    assert isinstance(payload, MethodOnePayload)
    with pytest.raises(AttributeError):
        cast(Any, payload).content_hash = "other"


def test_serialize_rejects_result_with_unsupported_nested_value() -> None:
    result = final_result("baseline_candidate")
    object.__setattr__(result.pricing, "pricing_engine_version", object())
    assert (
        failure(serialize_method_one_final_result(result)).code
        is ErrorCode.SERIALIZATION_ERROR
    )


def test_identity_rejects_wrong_type_and_propagates_stage_errors() -> None:
    assert isinstance(
        method_one_identity(cast(MethodOneFinalResult, object())), CalculationError
    )

    bad_configuration = final_result("baseline_candidate")
    object.__setattr__(
        bad_configuration.request.configuration, "formula_version", object()
    )
    assert isinstance(method_one_identity(bad_configuration), CalculationError)

    bad_input = final_result("baseline_candidate")
    object.__setattr__(bad_input.request, "match_id", object())
    assert isinstance(method_one_identity(bad_input), CalculationError)

    bad_result = final_result("baseline_candidate")
    object.__setattr__(bad_result.pricing, "match_id", object())
    assert isinstance(method_one_identity(bad_result), CalculationError)


def test_unsupported_dataclass_is_rejected() -> None:
    from dataclasses import dataclass as frozen

    @frozen
    class Unsupported:
        name: str

    assert isinstance(method_one_canonical_value(Unsupported("x")), CalculationError)
